apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::832947262004:user/jodi-ci
      username: jodi-ci
      groups:
        - system:masters